import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import crossmintLogo from '../public/crossmint-logo.svg'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>White Label Demo</title>
        <meta name="description" content="Generated by crossmint white label app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.crossmint.io/">White Label Demo!</a>
        </h1>

        <p className={styles.description}>
          Get started with our Beta version utilizing {' '}
          <code className={styles.code}>/api/v1-alpha1</code>
          endpoint
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Register &rarr;</h2>
            <p>Register and update your NFT collection with Crossmint

</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Checkout &rarr;</h2>
            <p>Begin the checkout process for a mint</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Create &rarr;</h2>
            <p>Create Crossmint custodial wallets for your customers!</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Transfer &rarr;</h2>
            <p>
              Help your clients transfer NFTs outside from the crossmint custodial wallet to another wallet 
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.crossmint.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className='pt-1'>
            <Image src={crossmintLogo} alt="Crossmint Logo" width={72} height={16} />
          </span>
          Crossmint
        </a>
      </footer>
    </div>
  )
}

export default Home
